"""add approval tracking fields

Revision ID: cfa521bd4f28
Revises: 5cc36f30984a
Create Date: 2025-09-20 23:35:56.735743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa521bd4f28'
down_revision: Union[str, Sequence[str], None] = '5cc36f30984a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('decision', sa.String(), nullable=True))
    op.add_column('approval_requests', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approval_requests', sa.Column('is_used', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_requests', 'is_used')
    op.drop_column('approval_requests', 'decided_at')
    op.drop_column('approval_requests', 'decision')
    # ### end Alembic commands ###
